---
variables:
  SANITY_TARGET_PYTHON: "3.10"

stages:
  - sanity
  - unit-tests
  - integration-tests
  - build
  - publish


.install_ansible:
  before_script: &install_ansible
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    - pip3 install -r requirements-dev.txt
  cache: &python_cache
    key: dataiku-dss-$CI_COMMIT_REF_SLUG
    paths:
      - "$CI_PROJECT_DIR/.cache/pip"
      - venv
    policy: pull

Run Sanity tests:
  tags:
    - shell
  before_script: *install_ansible
  cache: *python_cache
  stage: sanity
  script:
    - ansible-galaxy collection install .
    - cd ~/.ansible/collections/ansible_collections/dataiku/dss
    - ansible-test sanity --docker --python $SANITY_TARGET_PYTHON --coverage
