---
variables:
  PYTHON_IMAGE: "python:3.11"
  ANSIBLE_TEST_TARGET_PYTHON: 3.11
  DATAIKU_COMMUNITY_DOCKER_IMAGE: "dataiku/dss:14.0.0"

stages:
#  - sanity
#  - unit-tests
  - integration-tests
  - build
  - publish

.install_ansible:
  before_script: &install_ansible
    - pip3 install -r requirements.txt
    - pip3 install -r requirements-dev.txt
  cache: &python_cache
    key: dataiku-dss-$CI_COMMIT_REF_SLUG
    paths:
      - "$CI_PROJECT_DIR/.cache/pip"
      - venv
    policy: pull

.job_base:
  before_script: *install_ansible
  cache: *python_cache
  tags:
    - docker

#Run Sanity tests:
#  extends: .job_base
#  image: $PYTHON_IMAGE
#  stage: sanity
#  script:
#    - ansible-galaxy collection install .
#    - cd ~/.ansible/collections/ansible_collections/dataiku/dss
#    - ansible-test sanity --local --python $ANSIBLE_TEST_TARGET_PYTHON
#
#Run Unit tests:
#  extends: .job_base
#  image: $PYTHON_IMAGE
#  stage: unit-tests
#  script:
#    - ansible-galaxy collection install .
#    - cd ~/.ansible/collections/ansible_collections/dataiku/dss
#    - ansible-test units --local --python $ANSIBLE_TEST_TARGET_PYTHON

Run Integration tests:
  tags:
    - docker
  stage: integration-tests
  image: $DATAIKU_COMMUNITY_DOCKER_IMAGE
  before_script:
    # Start dss process
    - /home/dataiku/run.sh > /dev/null &
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - export PATH=/home/dataiku/.local/bin:$PATH
    - echo $PATH
  script:
    - ansible-galaxy collection install .
    - cd ~/.ansible/collection/ansible_collections/dataiku/dss
    - ansible-test integration --local dss_code_env
