---
namespace: dataiku
name: dss
version: 1.4.0
readme: README.md
authors:
- Jean-Bernard Jansen
- Augustin Ardon
description: Dataiku DSS ansible collection
license_file: LICENSE
tags: ["dataiku", "dss", "data-science-studio"]
dependencies: {}

repository: http://dataiku/dataiku-ansible-collection
homepage: https://github.com/dataiku/dataiku-ansible-collection
issues: https://github.com/dataiku/dataiku-ansible-collection/issues

manifest:
  directives:
    - include LICENSE
    - include COPYRIGHT
    - include CHANGELOG.md
    - include README.md
    - include requirements.txt
    - include requirements-dev.txt
    - recursive-include meta *
    - recursive-include docs *
    - recursive-include plugins *
    - recursive-include roles *
    - recursive-include tests *
    - global-exclude __pycache__
    - global-exclude *.pyc
