---
- name: Download InfluxData repository key
  become: true
  ansible.builtin.get_url:
    url: https://repos.influxdata.com/influxdata-archive.key
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-influxdata
    mode: "0644"
    checksum: "sha256:40557e261cdbdccac91a2dde474cbf101ef672661e64b211b711cc0b904d5dac"

- name: Add InfluxData package signing key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-influxdata

- name: Add telegraf repository
  become: true
  ansible.builtin.yum_repository:
    state: present
    name: influxdb
    description: InfluxDB Repository - RHEL $releasever
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-influxdata
    gpgcheck: true
    enabled: true
  register: telegraf_repo

- name: Update yum cache
  become: true
  ansible.builtin.yum:
    update_cache: yes
  when: telegraf_repo.changed

- name: Install telegraf latest version
  become: true
  ansible.builtin.yum:
    name: telegraf
    state: present
  when: telegraf_version == None

- name: Install telegraf specific version
  become: true
  ansible.builtin.yum:
    name: telegraf-{{ telegraf_version }}
    state: present
  when: telegraf_version != None
