---
- name: restart telegraf
  become: true
  ansible.builtin.systemd:
    name: telegraf
    state: restarted

- name: daemon reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
