---
telegraf_version: "1.30.1"
telegraf_conf_dss_datadir:
telegraf_conf_dss_installdir:
telegraf_conf_dss_id:
telegraf_conf_dss_node_type:
telegraf_conf_dss_story_enabled: false
telegraf_conf_use_legacy_graphite: true
telegraf_global_tags:
  dss_id: "{{ telegraf_conf_dss_id }}"
telegraf_hostname:
telegraf_conf_core_content: |
  [global_tags]
    {% for k,v in telegraf_global_tags.items() %}
    {{k}} = "{{v}}"
    {% endfor %}

  [agent]
    interval = "10s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "10s"
    flush_jitter = "0s"
    precision = "0s"
    hostname = "{{ telegraf_hostname | default(hostname) }}"
    omit_hostname = false
telegraf_conf_inputs_content: |
  [[inputs.cpu]]
    percpu = true
    totalcpu = true
    collect_cpu_time = false
    report_active = false
  [[inputs.mem]]
  [[inputs.swap]]
  [[inputs.kernel]]
  [[inputs.processes]]
  [[inputs.system]]
  [[inputs.chrony]]
  [[inputs.net]]
  [[inputs.netstat]]
  [[inputs.cgroup]]
    paths = ["/sys/fs/cgroup/memory/DSS", "/sys/fs/cgroup/memory/DSS/*", "/sys/fs/cgroup/memory/DSS/*/*"]
    files = ["memory.*usage*", "memory.limit_in_bytes"]
  [[inputs.disk]]
    ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "squashfs"]
  [[inputs.diskio]]
  [[inputs.linux_sysctl_fs]]
  [[inputs.net_response]]
    protocol = "tcp"
    address = "localhost:22"
  {% if docker_installed.rc == 0 %}
  [[inputs.docker]]
    perdevice = false
    perdevice_include = ["cpu", "network"]
    total = true
    total_include = ["cpu"]
  {% endif %}
  [[inputs.procstat]]
    interval = "30s"
    pattern = "dataiku-fm-agent"
    tag_with = ["pid"]
    [inputs.procstat.tags]
      dss_id = "{{ telegraf_conf_dss_id }}"
      dimension = "dataiku-fm-agent"
  [[inputs.procstat]]
    interval = "30s"
    pattern = "/usr/sbin/nginx.*-c {{ telegraf_conf_dss_datadir }}"
    tag_with = ["pid"]
    [inputs.procstat.tags]
      dss_id = "{{ telegraf_conf_dss_id }}"
      dimension = "dss-nginx"
  [[inputs.procstat]]
    interval = "30s"
  {% if telegraf_conf_dss_node_type == 'govern' %}
    pattern = "/bin/postmaster.*-D /data/pgsql-govern/data"
  {% else %}
    pattern = "/bin/postmaster.*-D /data/pgsql/data"
  {% endif %}
    tag_with = ["pid"]
    [inputs.procstat.tags]
      dss_id = "{{ telegraf_conf_dss_id }}"
      dimension = "dss-runtimedb"
  {% if telegraf_conf_dss_story_enabled | bool %}
  [[inputs.procstat]]
    interval = "30s"
    pattern = "docker-compose.*--file {{ telegraf_conf_dss_installdir }}/story/docker-compose\\.yml"
    tag_with = ["pid"]
    [inputs.procstat.tags]
      dss_id = "{{ telegraf_conf_dss_id }}"
      dimension = "dss-story"
  {% endif %}
  [[inputs.procstat]]
    interval = "30s"
  {% if telegraf_conf_dss_node_type == 'govern' %}
    pattern = "Ddku\\.governserver.*-cp {{ telegraf_conf_dss_datadir }}"
  {% else %}
    pattern = "Ddku\\.backend.*-cp {{ telegraf_conf_dss_datadir }}"
  {% endif %}
    tag_with = ["pid"]
    [inputs.procstat.tags]
      dss_id = "{{ telegraf_conf_dss_id }}"
      dimension = "dss-backend"
  {% if telegraf_conf_dss_node_type != 'govern' %}
  [[inputs.procstat]]
    interval = "30s"
    pattern = "Ddku\\.fek.*-cp {{ telegraf_conf_dss_datadir }}"
    tag_with = ["pid"]
    [inputs.procstat.tags]
      dss_id = "{{ telegraf_conf_dss_id }}"
      dimension = "dss-fek"
  [[inputs.procstat]]
    interval = "30s"
    pattern = "Ddku\\.jek.*-cp {{ telegraf_conf_dss_datadir }}"
    tag_with = ["pid"]
    [inputs.procstat.tags]
      dss_id = "{{ telegraf_conf_dss_id }}"
      dimension = "dss-jek"
  {% if telegraf_conf_use_legacy_graphite | bool is true %}
  [[inputs.socket_listener]]
    service_address = "tcp://127.0.0.1:9109"
    data_format = "graphite"
    templates = [
      "dss.*.server.jvm.threads.*.count                     measurement.dss_id.measurement.measurement.measurement.dimension.field",
      "dss.*.server.jvm.memory.pools.*.*                    measurement.dss_id.measurement.measurement.measurement.field.pool.dimension",
      "dss.*.server.jvm.memory.*.*                          measurement.dss_id.measurement.measurement.field.memory.dimension",
      "dss.*.server.jvm.memory.total.*                      measurement.dss_id.measurement.measurement.measurement.field.dimension",
      "dss.*.server.dku.jobs.activities.*                   measurement.dss_id.measurement.measurement.measurement.field.activity_state dimension=count",
      "dss.*.server.dku.jobs.*.*                            measurement.dss_id.measurement.measurement.field.job_state.dimension",
      "dss.*.server.dku.objectsCounts.global.*              measurement.dss_id.measurement.measurement.measurement.field.kind dimension=count",
      "dss.*.server.dku.ml.predictionTrain.*.*              measurement.dss_id.measurement.measurement.measurement.field.kind.dimension",
      "dss.*.server.dku.notifications.queue.*.size.*        measurement.dss_id.measurement.measurement.measurement.measurement.queue.size.dimension",
      "dss.*.server.dku.notifications.publish.*.*           measurement.dss_id.measurement.measurement.measurement.field.notification.dimension",
      "dss.*.server.dku.notifications.publish.*             measurement.dss_id.measurement.measurement.measurement.field.dimension notification=all",
    ]
  {% else %}
  [[inputs.prometheus]]
    urls = ["http://localhost:10000/public/api/metrics-prometheus"]
    username = "${DSS_API_KEY}"
  {% endif %}
  {% endif %}
telegraf_conf_outputs_content: |
  [[outputs.prometheus_client]]
telegraf_conf_additional_content: ""
